name: expense
networks:
  default:
    name: expense
volumes:
  mysql: {}

services:
  # docker run -d --name mongodb --network=roboshop mongodb:1
  mysql:
    image: mysql:v1
    container_name: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=ExpenseApp@1
    - MYSQL_DATABASE=transactions
    - MYSQL_USER=expense
    - MYSQL_PASSWORD=ExpenseApp@1
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume

  backend:
    image: backend:v1.0
    container_name: backend
    depends_on:
    - mysql

  # frontend:
  #   image: frontend:v1.0.0
  #   container_name: frontend
  #   depends_on:
  #   - backend
  #   ports:
  #     - "80:80"
